import { GLYPH_HEIGHT, GLYPH_WIDTH } from './decode'
import type { Font, Glyph, Pixel } from './types'

/**
 * The characters tools/mcm_decode.py uses for its ASCII dump. Keeping these
 * identical is what lets a fixture generated by Python verify this
 * implementation's pixel interpretation.
 */
const PIXEL_TO_CHAR: Record<Pixel, string> = {
  transparent: '.',
  white: '#',
  black: '-',
}

/** Render one glyph as GLYPH_HEIGHT lines of GLYPH_WIDTH characters. */
export function glyphToAscii(glyph: Glyph): string[] {
  const rows: string[] = []
  for (let y = 0; y < GLYPH_HEIGHT; y += 1) {
    let row = ''
    for (let x = 0; x < GLYPH_WIDTH; x += 1) {
      row += PIXEL_TO_CHAR[glyph.pixels[y * GLYPH_WIDTH + x]]
    }
    rows.push(row)
  }
  return rows
}

/**
 * Render a whole font in the exact format `python tools/mcm_decode.py <font>`
 * writes, including the `# glyph <dec> 0x<hex>` headers and the trailing
 * newline.
 */
export function fontToAscii(font: Font): string {
  const out: string[] = []
  font.forEach((glyph, index) => {
    const dec = String(index).padStart(3, ' ')
    const hex = index.toString(16).toUpperCase().padStart(2, '0')
    out.push(`# glyph ${dec} 0x${hex}`)
    out.push(...glyphToAscii(glyph))
  })
  return `${out.join('\n')}\n`
}
