"""Generate the per-variant icon overrides.

Two override sets, both small on purpose -- a variant is a set of
deliberate differences, not a second font:

``glyphs/icons_clean.py``
    For pilots who want familiar iconography. Only the icons whose Army Jay
    silhouette differs *in kind* from stock are overridden; the rest (RSSI
    bars, house, thermometer, crosshair, progress bar, battery states,
    arrows, AH ladder) are already stock-shaped and are left alone.

``glyphs/icons_simplified.py``
    For the high-readability variant. Drops internal detail from the
    fussiest pictograms, on the rule from section 4 that nothing should
    rely on more than 2px of internal detail.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from outline_art import sketch_to_art  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "glyphs"

# --------------------------------------------------------------------------
# clean: closer to the stock silhouettes
# --------------------------------------------------------------------------

CLEAN = {
    # Stock draws a throttle curve, not the letters THR.
    0x04: ("throttle curve", """
..#####.
.##...##
.##.....
..#####.
.....##.
##...##.
.#####..
""", 5),
    # Stock draws a map pin, not a pennant.
    0x11: ("map pin", """
..####..
.######.
##....##
##.##.##
##.##.##
##....##
.######.
..####..
...##...
....#...
""", 4),
    # Stock's AH decoration is a centred dash with end pips.
    0x13: ("dash with end pips", """
##.######.##
##.######.##
""", 8),
    # Stock draws a gauge arch with a needle.
    0x70: ("gauge arch", """
...####...
..######..
.##....##.
##..##..##
##.###..##
##......##
##......##
""", 5),
    # Stock's total-distance mark is an odometer ring with a tail.
    0x71: ("odometer ring", """
.######.
##....##
##....##
##....##
##....##
##..###.
.#####..
....###.
.....###
""", 4),
    # Stock's main battery is an outlined cell, not a filled one.
    0x97: ("outlined battery", """
..####..
########
##....##
##....##
##....##
##....##
##....##
##....##
##....##
##....##
##....##
########
""", 3),
}

# --------------------------------------------------------------------------
# simplified: for maximum legibility on a degraded analog feed
# --------------------------------------------------------------------------

SIMPLIFIED = {
    # Solid body, no struts: the 2px gaps close up first in noise.
    0x1E: ("satellite left, solid", """
.....#######
.....#######
..##########
..##########
..##########
.....#######
.....#######
""", 5),
    0x1F: ("satellite right, solid", """
#######.....
#######.....
##########..
##########..
##########..
#######.....
#######.....
""", 5),
    # Gauge without the needle -- the needle was the only 2px detail.
    0x70: ("gauge, no needle", """
..######..
.########.
##......##
##......##
##......##
##......##
""", 6),
    # Thermometer reduced to bulb and stem.
    0x7A: ("thermometer, plain", """
..####..
..####..
..####..
..####..
..####..
########
########
########
########
.######.
""", 4),
    # Stick-overlay sprites become solid blocks; a 4x4 ring is the
    # smallest thing in the font and the first to disappear.
    0x08: ("stick high, solid", "####\n####\n####\n####", 2),
    0x09: ("stick mid, solid", "####\n####\n####\n####", 7),
    0x0A: ("stick low, solid", "####\n####\n####\n####", 12),
    # A bigger centre cross.
    0x0B: ("stick centre, larger", """
...##...
...##...
...##...
########
########
...##...
...##...
...##...
""", 5),
}

HEADER = '''"""{doc}

Generated by ``tools/gen_sketches_variants.py``. These are overrides: any
index absent here falls through to ``glyphs/icons.py``.
"""

from __future__ import annotations

{name}: dict[int, str] = {{
'''


def emit(path: Path, doc: str, name: str, table: dict) -> None:
    body = [HEADER.format(doc=doc, name=name)]
    for index, (label, sketch, origin_y) in sorted(table.items()):
        body.append(f"    # 0x{index:02X}  {label}\n")
        art = sketch_to_art(sketch, origin_y=origin_y)
        body.append(f'    0x{index:02X}: """\n{art}\n""",\n')
    body.append("}\n")
    path.write_text("".join(body), encoding="utf-8", newline="\n")
    print(f"wrote {path} ({len(table)} overrides)")


def main() -> None:
    emit(
        OUT / "icons_clean.py",
        "Icon overrides for the `clean` variant -- closer to stock\n"
        "silhouettes, for pilots who want familiar iconography.",
        "ICONS_CLEAN",
        CLEAN,
    )
    emit(
        OUT / "icons_simplified.py",
        "Icon overrides for the `highreadability` variant -- internal\n"
        "detail removed so nothing depends on features a noisy analog feed\n"
        "will swallow.",
        "ICONS_SIMPLIFIED",
        SIMPLIFIED,
    )


if __name__ == "__main__":
    main()
