"""Generate ``MODIFIED_INDEXES.md`` from the glyph map and the built font.

The document is generated rather than maintained by hand so it cannot drift
from what actually shipped. ``validate.py`` check 8 reads its coverage
table back and fails the build if the declared changes and the real diff
against stock disagree, which closes the loop: the docs are tested.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Sequence

if __name__ == "__main__" and __package__ is None:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from glyphs.glyph_map import GLYPH_MAP, PROTECTED
from glyphs.logo import CRAFT_NAME_SLOTS, LOGO_TILES, WORDMARK_INDEXES
from mcm_decode import read_font
from mcm_encode import GLYPH_COUNT, TRANSPARENT, Glyph
from validate import DECLARATION_BEGIN, DECLARATION_END, format_index_ranges

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_FONT = REPO_ROOT / "fonts" / "armyjay_full.mcm"
DEFAULT_STOCK = REPO_ROOT / "assets" / "references" / "stock" / "default_v2.mcm"
DEFAULT_OUTPUT = REPO_ROOT / "MODIFIED_INDEXES.md"

ART_SOURCE = {
    "ascii": "glyphs/letters.py, numbers.py, punctuation.py",
    "icon": "glyphs/icons.py",
    "arrow": "glyphs/icons.py",
    "logo": "glyphs/logo.py (sliced from assets/logo_288x72.png)",
    "protected": "stock font, copied verbatim",
}


def is_blank(glyph: Glyph) -> bool:
    return all(char == TRANSPARENT for row in glyph.rows for char in row)


def describe_art(index: int, glyph: Glyph) -> str:
    """One phrase saying what was drawn at this index."""
    slot = GLYPH_MAP[index]
    if index in PROTECTED:
        return "unchanged stock glyph"
    if is_blank(glyph):
        return "intentionally blank"
    if slot.category == "logo":
        tile = " (in-flight wordmark)" if index in WORDMARK_INDEXES else ""
        return f"boot splash tile{tile}"
    if slot.category == "arrow":
        return "home arrow, Army Jay chunky style"
    if slot.category == "ascii":
        if 0x41 <= index <= 0x5A:
            return f"stencil capital {chr(index)}"
        if 0x30 <= index <= 0x39:
            digit = chr(index)
            extra = {
                "0": " (slashed, to separate it from O)",
                "1": " (flagged, to separate it from I)",
            }.get(digit, "")
            return f"stencil digit {digit}{extra}"
        return "stencil punctuation"
    return "Army Jay icon"


def build_document(
    glyphs: Sequence[Glyph], stock: Sequence[Glyph], font_name: str
) -> str:
    changed = [i for i in range(GLYPH_COUNT) if glyphs[i] != stock[i]]
    unchanged = [i for i in range(GLYPH_COUNT) if i not in changed]

    out: list[str] = []
    add = out.append

    add("# Modified indexes\n")
    add(
        "Every one of the 256 glyph indexes, what Betaflight uses it for, "
        "and what Army Jay draws there.\n"
    )
    add(
        f"Generated by `tools/gen_modified_indexes.py` from `{font_name}`. "
        "Do not edit by hand -- `tools/validate.py` check 8 reads the "
        "coverage table below and fails the build if it disagrees with the "
        "real diff against stock.\n"
    )
    add(
        f"**{len(changed)} of {GLYPH_COUNT} indexes differ from stock.** "
        f"The {len(unchanged)} that do not are listed too, with their "
        "reason.\n"
    )

    add("## Index allocation\n")
    add(
        "This is the table section 5 of the handoff asks for: proof that the "
        "boot splash range and the in-flight logo range do not conflict.\n"
    )
    add("| Range | Count | Purpose |")
    add("|---|---|---|")
    add("| `0x00` | 1 | `SYM_NONE`. Protected: blanks the screen on video init. |")
    add(
        "| `0x01`-`0x1F` | 31 | Status and unit icons, heading tape, "
        "stick overlay, satellites. |"
    )
    add(
        "| `0x20`-`0x5F` | 64 | ASCII: space, punctuation, digits, "
        "capitals. Meanings preserved. |"
    )
    add("| `0x60`-`0x6F` | 16 | Home direction arrows, 16 headings. |")
    add(
        "| `0x70`-`0x9F` | 48 | Crosshair, AH ladder, progress bar, battery "
        "states, unit labels. |"
    )
    wm_first, wm_last = WORDMARK_INDEXES[0], WORDMARK_INDEXES[-1]
    add(
        f"| `0xA0`-`0xFE` | {len(LOGO_TILES)} | Boot splash tiles "
        "(24 wide x 4 rows from `SYM_LOGO_START`). |"
    )
    add(
        f"| `0x{wm_first:02X}`-`0x{wm_last:02X}` | {len(WORDMARK_INDEXES)} | "
        "In-flight wordmark. **Nested inside the splash range**, not "
        "additional to it. |"
    )
    add(
        "| `0xFF` | 1 | `SYM_END_OF_FONT`. Protected, and the splash's "
        "bottom-right tile: left transparent so both hold. |"
    )
    add("")
    add(
        f"The in-flight block `0x{wm_first:02X}`-`0x{wm_last:02X}` is a "
        "subset of the splash block, so it costs nothing: the same tiles "
        "draw the splash at boot and the wordmark in flight. No ASCII slot "
        "is sacrificed.\n"
    )

    add("### Craft-name variant (Betaflight 4.4 through current)\n")
    add(
        "The optional `*_craftname.mcm` builds copy the wordmark tiles onto "
        "typeable ASCII indexes, because the craft-name field cannot reach "
        "the splash range. **These glyphs are lost in that variant only**; "
        "the default builds leave them intact.\n"
    )
    add(
        "Betaflight has no \"OSD Custom Elements\" feature -- that is INAV. "
        "On Betaflight `master` a custom message (`OSD_CUSTOM_MSG0`-`3`) can "
        "carry raw glyph indexes and needs no sacrifice; on 4.5 and earlier "
        "the craft name is the only route. See the README.\n"
    )
    slots = list(CRAFT_NAME_SLOTS)[: len(WORDMARK_INDEXES)]
    add("| Sacrificed index | Character | Receives tile |")
    add("|---|---|---|")
    for (slot_index, char), tile in zip(slots, WORDMARK_INDEXES):
        add(f"| `0x{slot_index:02X}` | `{char}` | `0x{tile:02X}` |")
    add("")
    add(
        "Craft name to type in Configurator: "
        f"`{''.join(c for _, c in slots)}`\n"
    )

    add("## Summary of changes\n")
    by_category: dict[str, list[int]] = {}
    for index in changed:
        by_category.setdefault(GLYPH_MAP[index].category, []).append(index)
    add("| Category | Changed | Indexes |")
    add("|---|---|---|")
    for category in sorted(by_category):
        indexes = by_category[category]
        add(
            f"| {category} | {len(indexes)} | "
            f"{format_index_ranges(indexes)} |"
        )
    add("")
    if unchanged:
        add(
            "Unchanged from stock: "
            f"{format_index_ranges(unchanged)} -- the protected pair plus "
            "indexes that are blank in both fonts.\n"
        )

    add("## Full coverage\n")
    add(
        "`vs stock` is `changed` where Army Jay draws something different "
        "from the stock font and `stock` where the bytes are identical.\n"
    )
    add(DECLARATION_BEGIN)
    add("")
    add("| Index | Betaflight symbol | Meaning | Army Jay art | vs stock |")
    add("|---|---|---|---|---|")
    for index in range(GLYPH_COUNT):
        slot = GLYPH_MAP[index]
        symbol = f"`{slot.symbol}`" if slot.symbol else "--"
        verdict = "changed" if index in changed else "stock"
        meaning = slot.meaning.replace("|", "\\|")
        art = describe_art(index, glyphs[index]).replace("|", "\\|")
        add(f"| `0x{index:02X}` | {symbol} | {meaning} | {art} | {verdict} |")
    add("")
    add(DECLARATION_END)
    add("")

    add("## Sources\n")
    add(
        "Index meanings are taken from betaflight/betaflight "
        "`src/main/drivers/osd_symbols.h` and cross-checked against "
        "betaflight-configurator `src/js/utils/osdFont.js`. Where the "
        "firmware header and the stock art disagree, the stock art wins, "
        "because that is what pilots actually see -- see `0x24`.\n"
    )
    return "\n".join(out) + "\n"


def _main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate MODIFIED_INDEXES.md")
    parser.add_argument("--font", type=Path, default=DEFAULT_FONT)
    parser.add_argument("--stock", type=Path, default=DEFAULT_STOCK)
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)

    if not args.font.exists():
        parser.error(f"{args.font} not built yet; run tools/build_font.py first")

    glyphs = read_font(args.font)
    stock = read_font(args.stock)
    args.output.write_text(
        build_document(glyphs, stock, args.font.name), encoding="utf-8", newline="\n"
    )
    changed = sum(1 for i in range(GLYPH_COUNT) if glyphs[i] != stock[i])
    print(f"wrote {args.output} ({changed}/{GLYPH_COUNT} indexes changed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
