"""Slice ``assets/logo_288x72.png`` into glyph tiles and write ``glyphs/logo.py``.

The boot splash occupies 96 tiles at 0xA0-0xFF (24 wide x 4 rows), which is
Betaflight's ``SYM_LOGO_START`` block. The last of those, 0xFF, is also the
reserved ``SYM_END_OF_FONT``, so this tool writes 95 tiles and requires the
bottom-right tile to be empty -- see STATUS.md for why both rules can hold
at once.

The same tiles serve the in-flight logo at no extra cost: the run of inked
tiles in the wordmark row reads correctly on its own, so pointing an OSD
Custom Element at those indexes draws the wordmark mid-flight without
sacrificing a single ASCII slot.

Input must use exactly the three colours Configurator's uploader defines:
pure green background, white, black. Anything else is rejected rather than
guessed at -- a stray anti-aliased pixel becomes a wrong pixel in a glyph.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Sequence

if __name__ == "__main__" and __package__ is None:
    sys.path.insert(0, str(Path(__file__).resolve().parent))

from PIL import Image

from mcm_encode import BLACK, GLYPH_HEIGHT, GLYPH_WIDTH, TRANSPARENT, WHITE, Glyph
from render import UPLOAD_PALETTE

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_INPUT = REPO_ROOT / "assets" / "logo_288x72.png"
DEFAULT_OUTPUT = REPO_ROOT / "glyphs" / "logo.py"

LOGO_START = 0xA0
TILES_HORIZ = 24
TILES_VERT = 4
TILE_COUNT = TILES_HORIZ * TILES_VERT  # 96, 0xA0..0xFF
RESERVED_INDEX = 0xFF
WORDMARK_ROW = 1

EXPECTED_SIZE = (GLYPH_WIDTH * TILES_HORIZ, GLYPH_HEIGHT * TILES_VERT)

#: RGB -> ASCII-art character, inverted from the uploader's own colour map.
COLOUR_TO_CHAR = {rgb: char for char, rgb in UPLOAD_PALETTE.items()}


class LogoError(ValueError):
    """Raised when the splash raster cannot be sliced safely."""


def load_raster(path: Path) -> Image.Image:
    image = Image.open(path).convert("RGB")
    if image.size != EXPECTED_SIZE:
        raise LogoError(
            f"{path}: expected {EXPECTED_SIZE[0]}x{EXPECTED_SIZE[1]}, "
            f"got {image.width}x{image.height}"
        )
    strays = {rgb for _, rgb in image.getcolors(maxcolors=1 << 16)} - set(
        COLOUR_TO_CHAR
    )
    if strays:
        listed = ", ".join(str(rgb) for rgb in sorted(strays)[:6])
        raise LogoError(
            f"{path}: contains {len(strays)} colour(s) outside the uploader's "
            f"palette: {listed}. Expected only black (0,0,0), white "
            f"(255,255,255) and green (0,255,0) -- re-export without "
            f"anti-aliasing."
        )
    return image


def slice_tiles(image: Image.Image) -> list[Glyph]:
    """Cut the raster into 96 tiles, in index order from 0xA0."""
    pixels = image.load()
    tiles: list[Glyph] = []
    for position in range(TILE_COUNT):
        row, col = divmod(position, TILES_HORIZ)
        x0, y0 = col * GLYPH_WIDTH, row * GLYPH_HEIGHT
        rows = [
            "".join(
                COLOUR_TO_CHAR[pixels[x0 + x, y0 + y]] for x in range(GLYPH_WIDTH)
            )
            for y in range(GLYPH_HEIGHT)
        ]
        tiles.append(Glyph(rows, name=f"0x{LOGO_START + position:02X}"))
    return tiles


def is_blank(glyph: Glyph) -> bool:
    return all(char == TRANSPARENT for row in glyph.rows for char in row)


def wordmark_run(tiles: Sequence[Glyph], row: int = WORDMARK_ROW) -> list[int]:
    """The contiguous run of inked tiles in the wordmark row, as indexes.

    This is the in-flight logo block. It is derived from the artwork rather
    than hard-coded, so moving the wordmark in ``make_logo.py`` moves the
    block with it and the allocation table stays true.
    """
    start = row * TILES_HORIZ
    inked = [
        position
        for position in range(start, start + TILES_HORIZ)
        if not is_blank(tiles[position])
    ]
    if not inked:
        raise LogoError(f"tile row {row} is empty -- no wordmark to point at")
    first, last = inked[0], inked[-1]
    gaps = [p for p in range(first, last + 1) if p not in inked]
    if gaps:
        # Interior blanks are fine (word spacing); they are still part of
        # the run and must be included so the element stays contiguous.
        pass
    return [LOGO_START + position for position in range(first, last + 1)]


def render_module(tiles: Sequence[Glyph], wordmark: Sequence[int]) -> str:
    first, last = wordmark[0], wordmark[-1]
    lines = [
        '"""Boot-splash tiles, sliced from ``assets/logo_288x72.png``.\n\n',
        "Generated by ``tools/slice_logo.py`` -- edit the PNG (or\n",
        "``tools/make_logo.py``, which draws it) and re-run, rather than\n",
        "editing the art here.\n\n",
        f"The splash occupies 0x{LOGO_START:02X}-0x{LOGO_START + TILE_COUNT - 1:02X} "
        f"({TILES_HORIZ} x {TILES_VERT} tiles). Index "
        f"0x{RESERVED_INDEX:02X} is reserved, so only "
        f"{TILE_COUNT - 1} tiles are written and the bottom-right tile is\n",
        "left transparent, exactly as the stock Betaflight splash does.\n\n",
        f"The in-flight logo is 0x{first:02X}-0x{last:02X} "
        f"({len(wordmark)} tiles): the run of inked tiles in row "
        f"{WORDMARK_ROW}, which\n",
        "reads correctly standalone. It costs no ASCII slots.\n",
        '"""\n\n',
        "from __future__ import annotations\n\n",
        f"LOGO_START = 0x{LOGO_START:02X}\n",
        f"TILES_HORIZ = {TILES_HORIZ}\n",
        f"TILES_VERT = {TILES_VERT}\n",
        f"RESERVED_INDEX = 0x{RESERVED_INDEX:02X}\n\n",
        "#: The in-flight wordmark block, contiguous and inside the splash\n"
        "#: range, so the two allocations cannot conflict.\n",
        f"WORDMARK_INDEXES = tuple(range(0x{first:02X}, 0x{last + 1:02X}))\n\n",
        "#: Craft-name fallback for Betaflight 4.4 and earlier, where the\n"
        "#: craft name can only reach typeable ASCII indexes. Built as an\n"
        "#: optional variant, never the default -- it overwrites these\n"
        "#: punctuation glyphs with wordmark tiles.\n",
        "CRAFT_NAME_SLOTS = (\n",
    ]
    fallback = craft_name_slots(len(wordmark))
    for index, char in fallback:
        lines.append(f"    (0x{index:02X}, {char!r}),\n")
    lines.append(")\n\n")
    lines.append("LOGO_TILES: dict[int, str] = {\n")
    for position, glyph in enumerate(tiles):
        index = LOGO_START + position
        if index == RESERVED_INDEX:
            continue
        row, col = divmod(position, TILES_HORIZ)
        note = " (wordmark)" if index in wordmark else ""
        lines.append(f"    # 0x{index:02X}  row {row}, column {col}{note}\n")
        lines.append(f'    0x{index:02X}: """\n{glyph.to_ascii()}\n""",\n')
    lines.append("}\n")
    return "".join(lines)


#: Characters that cannot appear in a craft name set over the CLI.
#: Betaflight strips everything from '#' onward as a comment before the
#: line is parsed (src/main/cli/cli.c, "Strip comment starting with # from
#: line"), so a name containing one is silently truncated. None of the
#: slots below use it.
CLI_HAZARDOUS = frozenset("#")

#: Punctuation that an OSD almost never needs, offered up so the 4.4
#: craft-name path has somewhere to put the wordmark. Order matters: the
#: first N are consumed, and their characters in order are the craft name
#: the pilot types.
_SACRIFICIAL = [
    (0x21, "!"), (0x22, '"'), (0x25, "%"), (0x26, "&"), (0x27, "'"),
    (0x28, "("), (0x29, ")"), (0x2A, "*"), (0x3C, "<"), (0x3E, ">"),
    (0x5B, "["), (0x5D, "]"),
]

_hazards = {c for _, c in _SACRIFICIAL} & CLI_HAZARDOUS
if _hazards:  # pragma: no cover - guards the table above
    raise AssertionError(
        f"sacrificial slots use CLI-hazardous characters: {sorted(_hazards)}"
    )


def craft_name_slots(count: int) -> list[tuple[int, str]]:
    if count > len(_SACRIFICIAL):
        raise LogoError(
            f"the wordmark needs {count} tiles but only {len(_SACRIFICIAL)} "
            "sacrificial ASCII slots are defined for the 4.4 craft-name path"
        )
    return _SACRIFICIAL[:count]


def _main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Slice the boot-splash raster into glyph tiles."
    )
    parser.add_argument("-i", "--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)

    image = load_raster(args.input)
    tiles = slice_tiles(image)

    reserved = tiles[RESERVED_INDEX - LOGO_START]
    if not is_blank(reserved):
        raise SystemExit(
            f"the bottom-right tile maps to 0x{RESERVED_INDEX:02X}, which is "
            "reserved, but it carries ink. Pull the artwork clear of the "
            "last 12x18 px of the raster."
        )

    wordmark = wordmark_run(tiles)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        render_module(tiles, wordmark), encoding="utf-8", newline="\n"
    )

    inked = sum(1 for t in tiles if not is_blank(t))
    print(f"wrote {args.output}")
    print(f"  {TILE_COUNT - 1} tiles written (0x{RESERVED_INDEX:02X} reserved)")
    print(f"  {inked} tiles carry ink")
    print(
        f"  in-flight wordmark: 0x{wordmark[0]:02X}-0x{wordmark[-1]:02X} "
        f"({len(wordmark)} tiles)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
